export const commonCopy = {
  'common.button.back': 'Back',
  'common.button.continue': 'Continue',
  'common.button.saveContinue': 'Save & continue',
  'common.button.saving': 'Saving…',
  'common.button.cancel': 'Cancel',
  'common.button.delete': 'Delete',
  'common.button.deleting': 'Deleting…',
  'common.button.confirm': 'Confirm',
  'common.button.close': 'Close',
  'common.unavailable': '—',
  'common.divider.or': 'or',
  'common.label.email': 'Email',
  'common.label.password': 'Password',
  'common.label.nameOptional': 'Name (optional)',
  'common.placeholder.yourName': 'Your name',
  'common.label.sex': 'Sex',
  'common.sex.male': 'male',
  'common.sex.female': 'female',
  'common.label.dateOfBirth': 'Date of birth',
  'common.label.height': 'Height',
  'common.label.feet': 'Feet',
  'common.label.inches': 'Inches',
  'common.units.useCm': 'Use cm',
  'common.units.useFtIn': 'Use ft/in',
  'common.units.useKg': 'Use kg',
  'common.units.useLbs': 'Use lbs',
  'common.units.kg': 'kg',
  'common.units.lbs': 'lbs',
  'common.units.cm': 'cm',
  'common.label.activityLevel': 'Activity level',
  'common.label.date': 'Date',
  'common.label.weight': 'Weight',
  'common.macro.protein': 'Protein',
  'common.macro.carbs': 'Carbs',
  'common.macro.fat': 'Fat',
  'common.macro.fiber': 'Fiber',
  'common.macro.tdee': 'TDEE',
  'common.macro.dailyTarget': 'Daily target',
  'common.macro.kcal': 'kcal',
  'common.macro.grams': 'g',
  'common.macro.lessThanOneGram': '<1g',
  'common.mealType.breakfast': 'Brekkie',
  'common.mealType.lunch': 'Lunch',
  'common.mealType.dinner': 'Dinner',
  'common.mealType.snack': 'Snack',
  'common.activity.sedentary.label': 'Sedentary',
  'common.activity.sedentary.description': 'Desk job, little exercise',
  'common.activity.lightlyActive.label': 'Lightly active',
  'common.activity.lightlyActive.description': '1–3 days/week',
  'common.activity.moderatelyActive.label': 'Moderately active',
  'common.activity.moderatelyActive.description': '3–5 days/week',
  'common.activity.veryActive.label': 'Very active',
  'common.activity.veryActive.description': '6–7 days/week',
  'common.activity.extraActive.label': 'Extra active',
  'common.activity.extraActive.description': 'Athlete or physical job',
  'common.error.notSignedIn': 'Not signed in',
  'common.brand.calsnap': 'CalSnap',
  'common.nav.main': 'Main',
  'common.nav.dashboard': 'Dashboard',
  'common.nav.log': 'Log',
  'common.nav.scan': 'Scan',
  'common.nav.progress': 'Progress',
  'common.nav.settings': 'Settings',
  'common.error.title': 'Something went wrong',
  'common.error.description': 'An unexpected error occurred. Please try again.',
  'common.button.retry': 'Try again',
  'common.action.log': 'Log',
  'common.action.view': 'View',
  'common.action.delete': 'Delete',
} as const;

export type CommonCopyKey = keyof typeof commonCopy;
