export const mealLogCopy = {
  'mealLog.title': "Today's Log",
  'mealLog.empty.title': 'No meals logged today.',
  'mealLog.empty.subtitle': 'Scan a meal to start your log.',
  'mealLog.empty.pastTitle': 'No meals on this day',
  'mealLog.empty.pastSubtitle': 'This day has no logged meals.',
  'mealLog.empty.action': 'Scan a meal',
  'mealLog.addMeal': 'Add {{mealType}}',
  'mealLog.addSheet.title': 'Add {{mealType}}',
  'mealLog.addSheet.scan': 'Scan a meal',
  'mealLog.addSheet.favorite': 'Use a favorite',
  'mealLog.confirm.deleteTitle': 'Delete meal?',
  'mealLog.confirm.delete': 'Delete this meal? This cannot be undone.',
  'mealLog.confirm.deleteAction': 'Delete meal',
  'mealLog.error.deleteFailed': 'Failed to delete meal. Try again.',
  'mealLog.detail.title': 'Meal detail',
  'mealLog.detail.notFound': 'Meal not found.',
  'mealLog.detail.loadFailed': 'Could not load meal.',
  'mealLog.detail.backToLog': 'Back to log',
  'mealLog.actions.delete': 'Delete',
  'mealLog.actions.deleting': 'Deleting…',
  'mealLog.actions.saveFavorite': 'Save to Favorites',
  'mealLog.actions.savedFavorite': 'Saved!',
  'mealLog.actions.noItems': 'All items removed — save is disabled. Cancel to restore or delete the meal.',
  'mealLog.favorites.title': 'Favorites',
  'mealLog.favorites.choose': 'Choose a favorite',
  'mealLog.favorites.empty': 'No favorites yet',
  'mealLog.favorites.emptySubtitle': 'Save a meal from your log to quickly log it again.',
  'mealLog.favorites.deleteConfirm': 'Delete favorite?',
  'mealLog.favorites.deleteDesc': 'This cannot be undone.',
  'mealLog.favorites.deleteAction': 'Delete',
  'mealLog.row.actions': 'Meal actions',
  'mealLog.row.empty': '(no items)',
  'mealLog.row.view': 'View',
  'mealLog.sheet.deleteItem': 'Delete {{item}}',
  'mealLog.dateNav.today': 'Today',
  'mealLog.error.loadTitle': 'Could not load meals',
  'mealLog.error.loadMessage': 'Something went wrong. Try again.',
  'mealLog.summary.total': 'Daily total',
  'mealLog.favorites.errorLoad': 'Failed to load favorites.',
  'mealLog.favorites.errorDelete': 'Failed to delete favorite.',
  'mealLog.sheet.error.logFailed': 'Could not save this meal. Try again.',
  'mealLog.sheet.error.invalidLogDate': 'Choose a date within the next three days to log this meal.',
  'mealLog.sheet.logToDate': 'Log to {{date}}',
  'mealLog.favorites.errorSave': 'Failed to save favorite. Try again.',
} as const;

export type MealLogCopyKey = keyof typeof mealLogCopy;
