export const mealLogCopy = {
  'mealLog.title': "Today's Log",
  'mealLog.empty.title': 'No meals logged today.',
  'mealLog.empty.subtitle': 'Scan a meal to start your log.',
  'mealLog.empty.action': 'Scan a meal',
  'mealLog.addMeal': 'Add {{mealType}}',
  'mealLog.confirm.deleteTitle': 'Delete meal?',
  'mealLog.confirm.delete': 'Delete this meal? This cannot be undone.',
  'mealLog.confirm.deleteAction': 'Delete meal',
  'mealLog.error.deleteFailed': 'Failed to delete meal. Try again.',
  'mealLog.detail.title': 'Meal detail',
  'mealLog.detail.notFound': 'Meal not found.',
  'mealLog.detail.loadFailed': 'Could not load meal.',
  'mealLog.detail.backToLog': 'Back to log',
  'mealLog.detail.noPhoto': 'No photo',
  'mealLog.actions.edit': 'Edit',
  'mealLog.actions.share': 'Share',
  'mealLog.actions.sharing': 'Sharing…',
  'mealLog.actions.delete': 'Delete',
  'mealLog.actions.deleting': 'Deleting…',
  'mealLog.row.actions': 'Meal actions',
  'mealLog.row.view': 'View',
  'mealLog.row.edit': 'Edit',
  'mealLog.share.title': 'CalSnap meal',
  'mealLog.share.error.generate': 'Failed to generate share image',
  'mealLog.share.error.failed': 'Failed to share meal card',
} as const;

export type MealLogCopyKey = keyof typeof mealLogCopy;
