export const mealLogCopy = {
  'mealLog.title': "Today's Log",
  'mealLog.empty.title': 'No meals logged today.',
  'mealLog.empty.subtitle': 'Scan a meal to start your log.',
  'mealLog.empty.pastTitle': 'No meals on this day',
  'mealLog.empty.pastSubtitle': 'This day has no logged meals.',
  'mealLog.empty.action': 'Scan a meal',
  'mealLog.addMeal': 'Add {{mealType}}',
  'mealLog.confirm.deleteTitle': 'Delete meal?',
  'mealLog.confirm.delete': 'Delete this meal? This cannot be undone.',
  'mealLog.confirm.deleteAction': 'Delete meal',
  'mealLog.error.deleteFailed': 'Failed to delete meal. Try again.',
  'mealLog.detail.title': 'Meal detail',
  'mealLog.detail.notFound': 'Meal not found.',
  'mealLog.detail.loadFailed': 'Could not load meal.',
  'mealLog.detail.backToLog': 'Back to log',
  'mealLog.detail.noPhoto': 'No photo',
  'mealLog.actions.delete': 'Delete',
  'mealLog.actions.deleting': 'Deleting…',
  'mealLog.actions.saveFavorite': 'Save to Favorites',
  'mealLog.actions.savedFavorite': 'Saved!',
  'mealLog.actions.noItems': 'All items removed — save is disabled. Cancel to restore or delete the meal.',
  'mealLog.favorites.title': 'Favorites',
  'mealLog.favorites.empty': 'No favorites yet',
  'mealLog.favorites.emptySubtitle': 'Save a meal from your log to quickly log it again.',
  'mealLog.favorites.useConfirm': 'Logged {{name}} for today',
  'mealLog.favorites.rename': 'Rename',
  'mealLog.favorites.renameLabel': 'Name this favorite',
  'mealLog.favorites.renamePlaceholder': 'e.g. Morning bagel',
  'mealLog.favorites.deleteConfirm': 'Delete favorite?',
  'mealLog.favorites.deleteDesc': 'This cannot be undone.',
  'mealLog.favorites.deleteAction': 'Delete',
  'mealLog.row.actions': 'Meal actions',
  'mealLog.row.view': 'View',
  'mealLog.dateNav.today': 'Today',
  'mealLog.summary.total': 'Daily total',
  'mealLog.favorites.errorLoad': 'Failed to load favorites.',
  'mealLog.favorites.errorDelete': 'Failed to delete favorite.',
  'mealLog.favorites.errorUse': 'Failed to log favorite meal.',
  'mealLog.favorites.logAction': 'Log for today',
  'mealLog.favorites.logging': 'Logging\u2026',
} as const;

export type MealLogCopyKey = keyof typeof mealLogCopy;
