export const progressCopy = {
  'progress.title': 'Progress',
  'progress.link.analytics': 'Dietary analytics →',
  'progress.logWeighIn': 'Log weigh-in',
  'progress.error.loadFailed': 'Could not load your progress.',
  'progress.error.partialLoad': 'Failed to load progress',
  'progress.header.current': 'Current',
  'progress.header.start': 'Start',
  'progress.header.goal': 'Goal',
  'progress.bar.label': 'Progress to goal',
  'progress.bar.a11y': '{{percent}}% toward goal',
  'progress.stats.lostSoFar': 'Lost so far',
  'progress.stats.toGoal': 'To goal',
  'progress.stats.weeklyRate': 'Weekly rate',
  'progress.stats.estimatedGoalDate': 'Estimated goal date',
  'progress.stats.logMore': 'Log more weigh-ins',
  'progress.stats.maintaining': 'Maintaining',
  'progress.stats.weeklyRateKg': '{{rate}} kg/week',
  'progress.stats.weeklyRateLbs': '{{rate}} lbs/week',
  'progress.chart.empty': 'Track your weight over time',
  'progress.chart.firstWeighIn': 'Log your first weigh-in',
  'progress.chart.goalLabel': 'Goal',
  'progress.chart.a11y.empty': 'No weigh-ins logged yet',
  'progress.chart.a11y.label': 'Weight progress chart',
  'progress.chart.a11y.summary':
    'Current weight {{current}}, {{direction}} from start, goal {{goal}}',
  'progress.chart.a11y.directionDown': 'down {{amount}}',
  'progress.chart.a11y.directionUp': 'up {{amount}}',
  'progress.chart.a11y.unchanged': 'unchanged',
  'progress.history.title': 'History',
  'progress.history.empty': 'No weigh-ins yet',
  'progress.history.emptyAction': 'Log weigh-in',
  'progress.history.bmiTdee': 'BMI {{bmi}} · TDEE {{tdee}} kcal',
  'progress.weighIn.title': 'Log weigh-in',
  'progress.weighIn.targetAdjust':
    'Your target adjusts from {{prev}} to {{next}} kcal/day (TDEE {{prevTdee}} → {{nextTdee}})',
  'progress.weighIn.save': 'Save weigh-in',
  'progress.weighIn.remindTomorrow': 'Remind me tomorrow',
  'progress.weighIn.error.saveFailed': 'Failed to save weigh-in',
  'progress.validation.weightRange': 'Weight must be within a valid range.',
  'progress.validation.futureDate': 'Weigh-in date cannot be in the future.',
} as const;

export type ProgressCopyKey = keyof typeof progressCopy;
