export const settingsCopy = {
  'settings.title': 'Settings',
  'settings.save': 'Save',
  'settings.saveProfile': 'Save profile',
  'settings.error.saveFailed': 'Failed to save profile',
  'settings.error.saveGeneric': 'Failed to save',
  'settings.error.profileLoad': 'Could not load your profile.',
  'settings.error.exportFailed': 'Failed to export data',
  'settings.error.deleteFailed': 'Failed to delete data',
  'settings.section.profile': 'Profile',
  'settings.profile.startingWeight': 'Starting weight ({{unit}})',
  'settings.profile.goalWeight': 'Goal weight ({{unit}})',
  'settings.profile.estimatedGoalDate': 'Estimated goal date',
  'settings.profile.tdee': 'TDEE: {{value}} kcal',
  'settings.profile.dailyTarget': 'Daily target: {{value}} kcal',
  'settings.profile.minimumIntake': 'Minimum safe intake: {{value}} kcal',
  'settings.section.macroTargets': 'Macro targets',
  'settings.macro.total': 'Total: {{sum}}%',
  'settings.macro.mustEqual100': '(must equal 100%)',
  'settings.section.units': 'Units',
  'settings.units.weightLbs': 'Weight in pounds',
  'settings.units.heightImperial': 'Height in feet and inches',
  'settings.section.weighInReminder': 'Weigh-in reminder',
  'settings.reminder.enable': 'Enable weigh-in reminder',
  'settings.section.yourData': 'Your data',
  'settings.data.export': 'Export data (CSV)',
  'settings.data.exporting': 'Exporting…',
  'settings.data.deleteAll': 'Delete all my data',
  'settings.deleteDialog.title': 'Delete all data?',
  'settings.deleteDialog.body':
    'This permanently deletes your meals, weigh-ins, profile, and photos. Your sign-in account is kept so you can start over from onboarding.',
  'settings.section.about': 'About',
  'settings.about.version': 'CalSnap version {{version}}',
  'settings.about.nih':
    'Calorie targets use formulas aligned with the NIH Body Weight Planner.',
  'settings.about.dga': 'Macro guidance follows the Dietary Guidelines for Americans.',
  'settings.section.account': 'Account',
  'settings.account.signOut': 'Sign out',
  'settings.validation.ageRange': 'Age must be between 16 and 90 years.',
  'settings.validation.goalBelowCurrent':
    'Goal weight must be below your current body weight.',
  'settings.validation.heightRange': 'Height must be between 120 and 230 cm.',
  'settings.validation.weightRange': 'Weight must be within a valid range.',
  'settings.validation.goalWeightRange': 'Goal weight must be within a valid range.',
  'settings.validation.macroSum': 'Macro percentages must sum to 100%.',
  'settings.notice.startingWeightReset':
    'Starting weight updated. Progress now measures from this new baseline.',
} as const;

export type SettingsCopyKey = keyof typeof settingsCopy;
