export const AppConstants = {
  Gemini: {
    model: 'gemini-2.5-flash',
    maxTokens: 4096,
    confidenceThreshold: 0.6,
  },
  Nutrition: {
    carbsCalPerGram: 4.0,
    proteinCalPerGram: 4.0,
    fatCalPerGram: 9.0,
    fiberCalPerGram: 2.0,
    alcoholCalPerGram: 7.0,
    fiberGramsPer1000Kcal: 14.0,
    defaultMacroProteinPct: 0.28,
    defaultMacroCarbsPct: 0.47,
    defaultMacroFatPct: 0.25,
  },
  Deficit: {
    defaultDeficitKcal: 350,
    minDeficitKcal: 250,
    maxDeficitKcal: 500,
    hardMaxDeficitKcal: 750,
    minCaloriesMale: 1500,
    minCaloriesFemale: 1200,
  },
  ActivityMultipliers: {
    sedentary: 1.2,
    lightlyActive: 1.375,
    moderatelyActive: 1.55,
    veryActive: 1.725,
    extraActive: 1.9,
  },
  Plateau: {
    weeksToDetect: 3,
    weightChangeThresholdKg: 0.23,
    weeklyMinimumDaySpacing: 6,
  },
  WeightProjection: {
    maxWeeks: 104,
  },
  USDA: {
    baseURL: 'https://api.nal.usda.gov/fdc/v1',
    demoAPIKey: 'DEMO_KEY',
  },
  Onboarding: {
    minAgeYears: 18,
    maxAgeYears: 90,
    minGoalDaysFromToday: 14,
    maxGoalDaysFromToday: 730,
  },
  Notifications: {
    weighInCategoryIdentifier: 'WEIGH_IN',
    dailyLogCategoryIdentifier: 'DAILY_LOG',
    defaultReminderWeekday: 0,
    defaultReminderHour: 8,
    defaultReminderMinute: 0,
    defaultDailyLogReminderHour: 20,
    defaultDailyLogReminderMinute: 0,
  },
  MealPhoto: {
    maxLongEdgePx: 1280,
    minLongEdgePx: 896,
    initialJPEGQuality: 0.72,
    minJPEGQuality: 0.5,
    preferredMaxBytes: 500_000,
    softMaxBytes: 750_000,
    hardMaxBytes: 1_000_000,
    outputMIMEType: 'image/jpeg',
    qualityRetrySteps: [0.72, 0.65, 0.6, 0.55, 0.5] as const,
    longEdgeRetrySteps: [1280, 1152, 1024, 896] as const,
  },
} as const;
